[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
requires-python = ">= 3.10.11"
name = "sampler_qa_checks_demo"
version = "1.0"
dependencies = [
    "pyyaml>=6.0",
    "pyodbc>=5.2",
]

[project.optional-dependencies]
hilltop = [
    "Hilltop>=7.0",
]
dev = [
    "pytest>=7.4.0",
    "pytest-mock>=3.11.0",
    "pytest-cov>=4.1.0",
    "pyodbc>=5.2",
    "pyyaml>=6.0",
]

[project.entry-points.'hilltop.sampler_qa_checks']
"sampler_qa_checks_demo" = 'sampler_qa_checks_demo:SamplerQAChecksPluginDemo'